name: Update Output Folder

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history so we can merge safely

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Remove old output folder
        run: rm -rf tabular_data/output

      - name: Run processor
        run: |
          # Replace this with your actual processing command
          python3 your_script.py

      - name: Skip files > 100 MB from commit
        run: |
          for file in $(find tabular_data/output -type f); do
            size=$(stat -c%s "$file")
            if [ $size -gt 104857600 ]; then
              echo "Skipping large file (>100MB): $file"
              git rm --cached "$file" || true
            fi
          done

      - name: Stage changes
        run: git add tabular_data/output

      - name: Commit changes (if any)
        run: |
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update generated output"
          fi

      - name: Pull latest main and merge
        run: |
          git fetch origin main
          git merge --no-edit origin/main || true

      - name: Push changes
        run: git push origin main
