name: Run Processor

on:
  workflow_dispatch:

  push:
    paths:
      - 'tabular_data/**'
      - 'collections/**'
      - '*.xml'

jobs:
  process:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Debug - find tabular_data directory
        run: |
          find . -type d

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Debug - list root directory
        run: ls -l

      - name: Install dependencies
        run: |
          cd tabular_data
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run processor
        run: |
          cd tabular_data
          source .venv/bin/activate
          python processor.py

      - name: Commit output changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add tabular_data/output
          git diff --quiet && git diff --staged --quiet || git commit -m "Update output from processor"
          git push
